# Variables
CXX = g++
CXXFLAGS = -Wall -std=c++11

# Target executable
TARGET = rideTheBus_program

# Source files
SRCS = main.cpp Card.cpp

# Object files
OBJS = main.o Card.o

# Default target
all: $(TARGET)

# Rule to link object files and create the executable
$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJS)

# Rule to compile main.cpp into main.o
main.o: main.cpp Card.h
	$(CXX) $(CXXFLAGS) -c main.cpp

# Rule to compile Point.cpp into Point.o
Card.o: Card.cpp Card.h
	$(CXX) $(CXXFLAGS) -c Card.cpp

# Clean up build files
clean:
	rm -f $(OBJS) $(TARGET)

# Phony targets (targets that aren't actual files)
.PHONY: all clean